spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/converter_db
    username: converter_db_admin
    password: 1Qwerty1
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate

server:
  port: 8080

cbr:
  url: http://www.cbr.ru/scripts/XML_daily.asp?date_req=
